### ISSUE TITLE
Using the old version of pop

### ISSUE THREAD

**Issue by kteb** [gobuffalo/buffalo-goth#11]
`buffalo-goth` and `buffalo-auth` are still using the old version of pop: `github.com/markbates/pop` instead of `github.com/gobuffalo/pop` the easiest PR is to simply replace the templates. 

A better approach is just to scan the models directory looking for either one of the imports. The first one you find wins and that’s what is printed.

I'll try to fix it soon.

**Comment by dflynn15** [comment]
For anyone interested, this has been resolved 👍 

Ref: https://github.com/gobuffalo/buffalo-goth/commit/0c490c9f4652b612b4aec93d5bd5e3a891abccec

**Comment by kteb** [comment]
As mention by @dflynn15 the problem was solved.
