### ISSUE TITLE
undefined: oauth2.RegisterBrokenAuthHeaderProvider

### ISSUE THREAD

**Issue by drnic** [gobuffalo/buffalo-goth#12]
```
$ go get -u github.com/gobuffalo/buffalo-goth
$ buffalo g goth github
      create  actions/auth.go
         run  go get github.com/markbates/goth/...
# github.com/markbates/goth/providers/wepay
../github.com/markbates/goth/providers/wepay/session.go:33:2: undefined: oauth2.RegisterBrokenAuthHeaderProvider
Error: exit status 2

$ buffalo g goth cloudfoundry
      create  actions/auth.go
         run  go get github.com/markbates/goth/...
# github.com/markbates/goth/providers/wepay
../github.com/markbates/goth/providers/wepay/session.go:33:2: undefined: oauth2.RegisterBrokenAuthHeaderProvider
Error: exit status 2
```

Using gobuffalo 12

**Comment by markbates** [comment]
This looks like an issue with Goth, which I don’t run anymore, you should open an issue there. The error occurs when it tries to get the Goth package. They might’ve broken something.

**Comment by drnic** [comment]
@markbates I looked at goth because it was suggested/mentioned in your docs/videos. If not goth, which oauth lib are you using?

**Comment by markbates** [comment]
It’s what I use, but I’m no longer the maintainer. It’s the omniauth of Go, so it’s definitely the one to use.

**Comment by markbates** [comment]
I haven’t updated to the latest version of Goth, it’s possible the new maintainers broke it. Don’t know though.

**Comment by drnic** [comment]
I did resolve this and other similar issues. Somehow I had a mess of old dependencies and they weren't being updated I guess.
