### ISSUE TITLE
buffalo generate doesn't find goth in app directory

### ISSUE THREAD

**Issue by JamieW87** [gobuffalo/buffalo-goth#18]
When I run `buffalo g goth twitter` in my buffalo app directory the standard help text for the generate function comes up. Like it doesn't recognise the goth package.
However if i run it in my src directory, it works succesfully (Tries opening the actions/app.go file, but fails obviously because it cant find it).
I have checked, rechecked and triple checked my GOPATH and PATH and everything is setup correctly.
I have "go get" the gobuffalo/buffalo-goth package and it is in the right place.
<img width="552" alt="Screenshot 2019-04-09 at 12 48 06" src="https://user-images.githubusercontent.com/23475197/55798009-be57e800-5ac5-11e9-9d47-383c23c4f7b1.png">

**Comment by dflynn15** [comment]
I'm still new to all of this, however I believe that you have to add the plugin with `buffalo plugins install github.com/gobuffalo/buffalo-goth`. If it is successful you should be able to see `goth` and `goth-auth` in the output of `buffalo g -h`. Also, in `./config/buffalo-plugins.toml` you should also see this:

```
[[plugin]]
  binary = "buffalo-goth"
  go_get = "github.com/gobuffalo/buffalo-goth"
```

From what I understand the buffalo cli looks in the projects configuration to help identify where the plugin is located. If it is outside of a project it'll just follow using `$GOPATH`. That's been my experience so far at least.

**Comment by JamieW87** [comment]
This worked! Thank you so much. How did you know this? I couldnt find it anywhere in the docs etc.

**Comment by markbates** [comment]
https://gobuffalo.io/en/docs/plugins
https://gobuffalo.io/en/docs/videos
