### ISSUE TITLE
Fail to resolve dependency github.com/gobuffalo/genny/movinglater/gotools

### ISSUE THREAD

**Issue by lancerushing** [gobuffalo/buffalo-goth#24]
Unable to install goth.  Dependency github.com/gobuffalo/genny/movinglater/gotools not found.

To verify I created  a clean $GOPATH directory:
```bash
$ mv "${GOPATH}" "${GOPATH}.bak"
$ mkdir "${GOPATH}" 
```

```bash
$ go get -u github.com/gobuffalo/buffalo-goth
package github.com/gobuffalo/genny/movinglater/gotools: cannot find package "github.com/gobuffalo/genny/movinglater/gotools" in any of:
        /usr/local/go/src/github.com/gobuffalo/genny/movinglater/gotools (from $GOROOT)
        /home/lance/go/src/github.com/gobuffalo/genny/movinglater/gotools (from $GOPATH)
package github.com/gobuffalo/genny/movinglater/gotools/gomods: cannot find package "github.com/gobuffalo/genny/movinglater/gotools/gomods" in any of:
        /usr/local/go/src/github.com/gobuffalo/genny/movinglater/gotools/gomods (from $GOROOT)
        /home/lance/go/src/github.com/gobuffalo/genny/movinglater/gotools/gomods (from $GOPATH)
```

If you want, let me know where the "movinglater" packaged moved to, and I fix and submit a PR.

**Comment by camstuart** [comment]
Looks like that package disappeared during work on `genny` (23 Jun 2019) you can see it here:

https://github.com/gobuffalo/genny/tree/66e3b56e4688a68c9ff8ef0daef16ab6f0ca9328

I like the "movinglater" package name, kinda gave it away for me. The question is, where should we move it to? feels like this should either live under `genny` where it was or perhaps: `github.com/gobuffalo/buffalo-gotools` I guess it depends on whether other buffalo packages need to use it independently.

We will have to wait and hear what @markbates had in mind during this commit

**Comment by markbates** [comment]
There’s already a PR to fix this https://github.com/gobuffalo/buffalo-goth/pull/23 it needs attention I can’t give it for a few days, if anyone wants to finish that would be great. 

In the meantime might I suggest using Modules instead of GOPATH this will “self fix” if you do.

**Comment by krotovic** [comment]
> There’s already a PR to fix this #23 it needs attention I can’t give it for a few days, if anyone wants to finish that would be great.
> 
> In the meantime might I suggest using Modules instead of GOPATH this will “self fix” if you do.

Tried to fixed it in #25

**Comment by paqman85** [comment]
Has this been resolved? I'm stuck on the same error.

**Comment by paqman85** [comment]
I'm using modules,  Buffalo v.0.15.3 on a windows 10 machine. I've tried both with and without the -v; with similar results. I posted the readout I'm getting below.

`$ go get -u -v github.com/gobuffalo/buffalo-goth
go: finding golang.org/x/crypto latest
go: finding golang.org/x/sys latest
build github.com/gobuffalo/buffalo-goth: cannot load github.com/gobuffalo/genny/movinglater/gotools: module github.com/gobuffalo/genny@latest found (v0.4.1), but does not contain package github.com/gobuffalo/genny/movinglater/gotools
`

**Comment by krotovic** [comment]
> Has this been resolved? I'm stuck on the same error.

No, I'm waiting for review of my PR #25 from @markbates

**Comment by paqman85** [comment]
It works! Thanks for the nod to PR #25

**Comment by paqman85** [comment]
I see that PR#25 is accepted - error is still the same after I update the version number. Anything else I can try?

**Comment by krotovic** [comment]
My PR #25 was for fixing #23 but i see that it has some other issues so maybe i propose to merge it in master to resolve this issue first and then #23. I'll try to look into it little bit and if I fail to resolve it then I'll make my fix to master.

**Comment by mauza** [comment]
Is there a workaround? I'm new to go and just wanted to create a simple api with google oauth, but can't seem to get past the install of this package. 
```
➜ go get -u -v github.com/gobuffalo/buffalo-goth
go: finding golang.org/x/crypto latest
go: finding golang.org/x/sys latest
build github.com/gobuffalo/buffalo-goth: cannot load github.com/gobuffalo/genny/movinglater/gotools: module github.com/gobuffalo/genny@latest found (v0.6.0), but does not contain package github.com/gobuffalo/genny/movinglater/gotools
```

**Comment by markbates** [comment]
Try not using -u
--
Mark Bates

**Comment by mauza** [comment]
Thank you for the suggestion :pray:  I get a similar error without the first two lines:
```
➜ go get github.com/gobuffalo/buffalo-goth   
build github.com/gobuffalo/buffalo-goth: cannot load github.com/gobuffalo/genny/movinglater/gotools: module github.com/gobuffalo/genny@latest found (v0.6.0), but does not contain package github.com/gobuffalo/genny/movinglater/gotools
```
