### ISSUE TITLE
Invalid provider declaration for Auth0

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo-goth#3]
When generating Auth0 provider authentication on the init block inside auth.go, this generator is using an invalid signature to initialize the auth0 provider (requires more arguments):

```go
...
goth.UseProviders(
    auth0.New(os.Getenv("AUTH0_KEY"), os.Getenv("AUTH0_SECRET"), fmt.Sprintf("%s%s", App().Host, "/auth/auth0/callback")),
)
```
This ends up not compiling and should be:

```go
goth.UseProviders(
    auth0.New(os.Getenv("AUTH0_KEY"), os.Getenv("AUTH0_SECRET"), fmt.Sprintf("%s%s", App().Host, "/auth/auth0/callback"), os.Getenv("AUTH0_DOMAIN"), os.Getenv("AUTH0_SCOPE")),
)

```

**Comment by dflynn15** [comment]
Should have been closed by https://github.com/gobuffalo/buffalo-goth/pull/4.
