### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by zulhfreelancer** [gobuffalo/buffalo-goth#33]
Hi. The https://gobuffalo.io/docs/generators#goth link in the README file is pointed to non existent page. I don't know what's the correct one. Hope this issue can be fixed. Thanks.

**Comment by zulhfreelancer** [comment]
Related to https://github.com/gobuffalo/buffalo-goth/pull/19/files (https://gobuffalo.io/en/docs/goth/)?

**Comment by sio4** [comment]
Thanks for the reporting!
