### ISSUE TITLE
The "goth-auth" generator is applying the auth.go "goth" template instead

### ISSUE THREAD

**Issue by tcarreira** [gobuffalo/buffalo-goth#37]
Steps to reproduce (any provider works):
```
buffalo generate goth-auth github
``` 

The app fails to compile.

The generated `auth.go` file does not have the required methods (added in `app.go`):

```
func AuthCallback(c buffalo.Context) error {} // This is only partially implemented, using the simple "goth" template instead
func AuthDestroy(c buffalo.Context) error {}
func SetCurrentUser(next buffalo.Handler) buffalo.Handler {}
func Authorize(next buffalo.Handler) buffalo.Handler {}
```

**Comment by tcarreira** [comment]
actually, I believe this is the same as https://github.com/gobuffalo/buffalo-goth/issues/34

**Comment by Flexicon** [comment]
Did you find any solution or work around for this @tcarreira ?

**Comment by tcarreira** [comment]
> Did you find any solution or work around for this @tcarreira ?

Yes I did. 
I manually copy/pasted the template from https://github.com/gobuffalo/buffalo-goth/blob/master/genny/auth/templates/actions/auth.go.tmpl

I couldn't figure where to fix this (I don't have much free time to help it now). And I think this is very trivial to fix if you are familiar with the code already.

**Comment by Flexicon** [comment]
Great stuff @tcarreira ! I'll look into preparing a PR for this.

**Comment by sio4** [comment]
I think this issue was already fixed during migration to `embed`. Closing.
