### ISSUE TITLE
could not find a matching session for this request

### ISSUE THREAD

**Issue by kswope** [gobuffalo/buffalo-goth#6]
This happens at the oauth callback stage.  

I've tested this for both facebook and gplus (the two providers that let me whitelist multiple callback urls)

These are functioning, fulling working oauth accounts that are used in production already (using omniauth)

Here is the oauth callback 'errortrace', doesn't look helpful
```
could not find a matching session for this request
github.com/markbates/pop.(*Connection).Transaction.func1
/home/kevin/go/src/github.com/markbates/pop/connection.go:122
github.com/markbates/pop.(*mysql).Lock
/home/kevin/go/src/github.com/markbates/pop/mysql.go:118
github.com/markbates/pop.(*Connection).Transaction
/home/kevin/go/src/github.com/markbates/pop/connection.go:109
github.com/gobuffalo/buffalo/middleware.glob..func1.1.1
/home/kevin/go/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:22
github.com/gobuffalo/buffalo/middleware/csrf.glob..func1.1
/home/kevin/go/src/github.com/gobuffalo/buffalo/middleware/csrf/csrf.go:119
github.com/gobuffalo/buffalo/middleware.ParameterLogger.func1
/home/kevin/go/src/github.com/gobuffalo/buffalo/middleware/param_logger.go:28
github.com/gobuffalo/buffalo/middleware/ssl.ForceSSL.func1.1
/home/kevin/go/src/github.com/gobuffalo/buffalo/middleware/ssl/ssl.go:26
github.com/gobuffalo/buffalo.sessionSaver.func1
/home/kevin/go/src/github.com/gobuffalo/buffalo/session.go:70
github.com/gobuffalo/buffalo.RequestLoggerFunc.func1
/home/kevin/go/src/github.com/gobuffalo/buffalo/request_logger.go:51
github.com/gobuffalo/buffalo.(*App).PanicHandler.func1
/home/kevin/go/src/github.com/gobuffalo/buffalo/errors.go:69
github.com/gobuffalo/buffalo.RouteInfo.ServeHTTP
/home/kevin/go/src/github.com/gobuffalo/buffalo/handler.go:75
github.com/gobuffalo/buffalo.(*RouteInfo).ServeHTTP
<autogenerated>:1
github.com/gorilla/mux.(*Router).ServeHTTP
/home/kevin/go/src/github.com/gorilla/mux/mux.go:150
github.com/markbates/refresh/refresh/web.ErrorChecker.func1
/home/kevin/go/src/github.com/markbates/refresh/refresh/web/web.go:23
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:1918
github.com/gobuffalo/buffalo.(*App).ServeHTTP
/home/kevin/go/src/github.com/gobuffalo/buffalo/app.go:151
net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:2619
net/http.(*conn).serve
/usr/local/go/src/net/http/server.go:1801
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:2337
github.com/gobuffalo/buffalo.sessionSaver.func1
/home/kevin/go/src/github.com/gobuffalo/buffalo/session.go:72
github.com/gobuffalo/buffalo.RequestLoggerFunc.func1
/home/kevin/go/src/github.com/gobuffalo/buffalo/request_logger.go:51
github.com/gobuffalo/buffalo.(*App).PanicHandler.func1
/home/kevin/go/src/github.com/gobuffalo/buffalo/errors.go:69
github.com/gobuffalo/buffalo.RouteInfo.ServeHTTP
/home/kevin/go/src/github.com/gobuffalo/buffalo/handler.go:75
github.com/gobuffalo/buffalo.(*RouteInfo).ServeHTTP
<autogenerated>:1
github.com/gorilla/mux.(*Router).ServeHTTP
/home/kevin/go/src/github.com/gorilla/mux/mux.go:150
github.com/markbates/refresh/refresh/web.ErrorChecker.func1
/home/kevin/go/src/github.com/markbates/refresh/refresh/web/web.go:23
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:1918
github.com/gobuffalo/buffalo.(*App).ServeHTTP
/home/kevin/go/src/github.com/gobuffalo/buffalo/app.go:151
net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:2619
net/http.(*conn).serve
/usr/local/go/src/net/http/server.go:1801
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:2337
```
The error message comes from 
github.com/markbates/goth/gothic/gothic.go

```
     func getSessionValue(session *sessions.Session, key string) (string, error) {                                       
       value := session.Values[key]                                                                                      
       if value == nil {                                                                                                 
         return "", fmt.Errorf("could not find a matching session for this request")                                     
       } 
```
I'm working my through understanding whats going on, but I have figured out that the 'key' should be either gplus or facebook, but its missing from the session at that point.

I'm still investigating.  I'm new to golang so I'm using this as a chance to get familiar with debugging, but its going slowly.

BTW, we're going to have to put some warning on running this more than once, its destructive. 
```
buffalo g goth x y z
```

**Comment by markbates** [comment]
Make sure your “host” of the app matches the exact host registered with the provider. That’s usually the solution to this. 

Example, Buffalo defaults the dev host to http://127.0.0.1:3000 unless you tell if differently. If you register 127x with the provider, but you start your request with localhost you’ll get this error. The session cookie was dropped on localhost, but the callback comes to 127x, no session cookie. 

Check all that and see if it fixes the issue for you.

**Comment by kswope** [comment]
Yea that was it, I should I realized when the session was disappearing that I was switching cookies.

Buffalo might bind to 127 but everybody uses localhost:3000, even the tutorial has localhost:3000!

I'm convinced everybody is going to have this same problem if they use buffalo-goth, how could they not?

Ok I see, if I use this everything works as expected from a rails point of view.
```
HOST=http://localhost:3000 buffalo dev
```

So for any newcomer who probably will access buffalo through localhost:3000, this speedbump is inevitable.

I've read somewhere else that buffalo binds to 127 because some oauth providers might reject localhost redirects?  I know my two favorites (because they allow multiple redirects) facebook and gplus, allow localhost.

**Comment by markbates** [comment]
A lot of them don’t accept localhost, like GitHub, for example. So that’s why 127 is the default host. It’s only when doing oauth stuff is it actually and issue, but that’s another story. 

Doc PRs are always welcome. Please! :)

**Comment by kswope** [comment]
I couldn't find a clever way of auto detecting this problem, so why not just a more helpful error message?

```
could not find a matching session for this request
```


```
OAuth problem: could not find a matching session for this request, check if redirect URL and callback URL have same domain:  different domain --> different cookies --> different sessions
```

**Comment by markbates** [comment]
A better error message would be great!

**Comment by briantbates** [comment]
I used the auth0 generator for gothic right after a buffalo new --api generator. After a long time of debugging gothic.go in mark's package, I realized I still had the SessionStore initializing in the buffalo settings.

I'm not sure how this changes other processes but it stopped the error from occurring. 
```
buffalo.New(buffalo.Options{
			Env: ENV,
			SessionStore: sessions.Null{}
...
```
to: 
```
buffalo.New(buffalo.Options{
			Env:  ENV,
	...

**Comment by Baggerone** [comment]
@kswope, May I ask how you got a stack trace with the error message?  We just see the error, but not the stack trace.

**Comment by boonsanti** [comment]
Hi,Every one

I got this problem when I run APP on production with docker.It's work on http://127.0.0.1:3000 with google oauth but not work on production and got "could not find a matching session for this request" error message.

Thanks in advance.

Boon

**Comment by Baggerone** [comment]
@boonsanti, can you double check your configs/settings to ensure the right url's  are being used for the response from google oauth?

**Comment by boonsanti** [comment]
> @boonsanti, can you double check your configs/settings to ensure the right url's are being used for the response from google oauth?

Thank you @Baggerone, It's work when I run WEB APP with https.

Sorry,I deleted my question comment.
